'use client'
import Topnavbar from '@/components/topnavbar'
import './globals.css'
import Footer from '@/components/footer'
import Head from 'next/head'
import { Providers } from './providers'


// export const metadata = {
//   title: 'Yaw Precious | Product Designer',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {


  return (
    <html lang="en">
      <head>
        <meta name="description" content="Hello I'm Yaw Precious, a Product Designer.
        I love to untangle difficult problems by tagging along from conceptualisation to 
        the actualisation of a product. Skills: Brand Strategy & Design | User Research | UI Design | ReactJs | NextJs <typescript>" />
        <meta charSet="UTF-8" />

      </head>

      <body className='flex justify-center'>
        <Providers>
          <main className='xl:w-[90rem] w-full'>
            <Topnavbar />
            {children}
            <Footer />
          </main>
        </Providers>
      </body>
    </html>

  )
}
